# Generated by Django 4.2.3 on 2023-07-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
